products:
  - id: "00000001"
    name: "Продукт 1"
    price: 10.0
    weight: 1.5
  - id: "00000002"
    name: "Продукт 2"
    price: 20.0
    weight: 2.0
  - id: "00000003"
    name: "Продукт 3"
    price: 30.0
    weight: 2.5
